version: 1.2
workflows:
   - subclass: WDL
     publish: True
     primaryDescriptorPath: /publicTreeSamplePlacement.wdl
     testParameterFiles: <String Array>
     authors:
       - name: Marc Perry
         email: madperry@ucsc.edu
         affiliation: University of California, Santa Cruz
     filters:
       branches: main
