version: 1.2
workflows:
   - name: publicTreeSamplePlacement
     subclass: WDL
     publish: True
     primaryDescriptorPath: /publicTreeSamplePlacement.wdl
     authors:
       - name: Marc Perry
         email: madperry@ucsc.edu
         affiliation: University of California, Santa Cruz
     filters:
       branches: 
         - main
