version: 1.2
workflows:
 - name: publicTreeSamplePlacementCCPHL
   subclass: WDL
   primaryDescriptorPath: /publicTreeSamplePlacement.wdl
   testParameterFiles:
    - empty.json
 - name: matUtilsTestCCPHL
   subclass: WDL
   primaryDescriptorPath: /matUtilsTest.wdl
   testParameterFiles:
    - empty.json